language: python

install:
  - pip install tox

services:
  - redis-server

script:
  - pep8 stdnet --exclude stdnet/apps/searchengine/processors
  - tox

notifications:
  email: false

# Only test master and dev
branches:
  only:
    - master
    - dev
